version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"

  orders-db:
    image: postgres:16
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: orders
      POSTGRES_PASSWORD: orders
    ports:
      - "5433:5432"

  payments-db:
    image: postgres:16
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
    ports:
      - "5434:5432"

  payments-service:
    build:
      context: .
      dockerfile: payments-service/Dockerfile
    environment:
      PAYMENTS_HTTP_ADDR: :8081
      PAYMENTS_DATABASE_URL: postgres://payments:payments@payments-db:5432/payments?sslmode=disable
      PAYMENTS_RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
      ORDERS_EXCHANGE: orders.events
      PAYMENTS_EXCHANGE: payments.events
      PAYMENTS_ORDERS_QUEUE: payments.orders
    depends_on:
      - payments-db
      - rabbitmq
    ports:
      - "8081:8081"

  orders-service:
    build:
      context: .
      dockerfile: orders-service/Dockerfile
    environment:
      ORDERS_HTTP_ADDR: :8080
      ORDERS_DATABASE_URL: postgres://orders:orders@orders-db:5432/orders?sslmode=disable
      ORDERS_RABBIT_URL: amqp://guest:guest@rabbitmq:5672/
      ORDERS_EXCHANGE: orders.events
      PAYMENTS_EXCHANGE: payments.events
      ORDERS_PAYMENTS_QUEUE: orders.payment-results
    depends_on:
      - orders-db
      - rabbitmq
    ports:
      - "8080:8080"
